name: Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sbt box2dDemoJS/fullOptJS box2dJVM/doc
          mkdir -p docs/js
          cp modules/box2d-demo/js/target/scala-2.13/box2d-demo-opt.js* docs/js/
          cp -r modules/box2d/jvm/target/scala-2.13/api docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
